CREATE TABLE IF NOT EXISTS `mappings`
(
    `endpoint` VARBINARY(32) NOT NULL,
    `host`     INT        NOT NULL,
    `type`     INT        NOT NULL,
    PRIMARY KEY (`endpoint`, `type`)
);

CREATE TABLE `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created` timestamp NULL DEFAULT current_timestamp(),
  `updated` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `jtl_id` int(11) NOT NULL,
  `sku` varchar(255) DEFAULT '',
  `stock` int(11) DEFAULT NULL,
  `supplier_stock` int(11) DEFAULT NULL,
  `permit_negative_stock` tinyint(1) unsigned DEFAULT NULL,
  `delivery_time` int(11) unsigned DEFAULT NULL,
  `handling_time` int(11) unsigned DEFAULT NULL,
  `product_name` varchar(255) DEFAULT '',
  `vivino_name` varchar(255) DEFAULT '',
  `bottle_price` double DEFAULT NULL,
  `bottle_size` double DEFAULT NULL,
  `bottle_quantity` int(11) DEFAULT NULL,
  `link` varchar(255) DEFAULT '',
  `image` varchar(255) DEFAULT '',
  `gtin_vke` varchar(255) DEFAULT '',
  `wine_vintage` varchar(255) DEFAULT '',
  `wine_color` varchar(255) DEFAULT '',
  `country` varchar(255) DEFAULT '',
  `lbm_zutaten` varchar(255) DEFAULT '',
  `alkohol` double DEFAULT NULL,
  `restzucker` double DEFAULT NULL,
  `lbm_brennwert_kj` double DEFAULT NULL,
  `allergen_sulfite` tinyint(1) DEFAULT NULL,
  `allergen_milch` tinyint(1) DEFAULT NULL,
  `allergen_ei` tinyint(1) DEFAULT NULL,
  `allergen_erdnuss` tinyint(1) DEFAULT NULL,
  `allergen_fisch` tinyint(1) DEFAULT NULL,
  `allergen_albumin` tinyint(1) DEFAULT NULL,
  `allergen_gluten` tinyint(1) DEFAULT NULL,
  `allergen_kasein` tinyint(1) DEFAULT NULL,
  `allergen_krebstier` tinyint(1) DEFAULT NULL,
  `allergen_lupinen` tinyint(1) DEFAULT NULL,
  `allergen_lysozym` tinyint(1) DEFAULT NULL,
  `allergen_nuss` tinyint(1) DEFAULT NULL,
  `allergen_sellerie` tinyint(1) DEFAULT NULL,
  `allergen_senf` tinyint(1) DEFAULT NULL,
  `allergen_sesam` tinyint(1) DEFAULT NULL,
  `allergen_soja` tinyint(1) DEFAULT NULL,
  `allergen_weichtier` tinyint(1) DEFAULT NULL,
  `allergen_farbstoffe` tinyint(1) DEFAULT NULL,
  `allergen_aromen` tinyint(1) DEFAULT NULL,
  `allergen_konservierungsstoffe` tinyint(1) DEFAULT NULL,
  `allergen_antioxidanzien` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `properties` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `property_name` varchar(255) DEFAULT NULL,
  `property_id` int(11) unsigned DEFAULT NULL,
  `value_name` varchar(255) DEFAULT NULL,
  `value_id` int(22) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `property_value` (`property_id`,`value_id`)
);

CREATE TABLE `weinsys_attributes` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `label` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`)
);

CREATE TABLE `weinsys_properties` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `group_name` varchar(255) DEFAULT NULL,
  `group_label` varchar(255) DEFAULT NULL,
  `value_name` varchar(255) DEFAULT NULL,
  `value_label` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `country_names` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `country_name_de` varchar(255) DEFAULT NULL,
  `country_name_en` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `country_name_de` (`country_name_de`)
);

INSERT INTO `country_names` (`country_name_de`, `country_name_en`)
VALUES
	('Deutschland', 'Germany'),
	('Arabische Emirate', 'Arab Emirates'),
	('Australien', 'Australia'),
	('Belgien', 'Belgium'),
	('Dänemark', 'Denmark'),
	('Finnland', 'Finland'),
	('Frankreich', 'France'),
	('Griechenland', 'Greece'),
	('Großbritannien', 'Great Britain'),
	('Irland', 'Ireland'),
	('Island', 'Iceland'),
	('Italien', 'Italy'),
	('Japan', 'Japan'),
	('Kanada', 'Canada'),
	('Luxemburg', 'Luxembourg'),
	('Namibia', 'Namibia'),
	('Niederlande', 'Netherlands'),
	('Norwegen', 'Norway'),
	('Österreich', 'Austria'),
	('Portugal', 'Portugal'),
	('Schweden', 'Sweden'),
	('Schweiz', 'Switzerland'),
	('Spanien', 'Spain'),
	('USA', 'Usa'),
	('Liechtenstein', 'Liechtenstein'),
	('Polen', 'Poland'),
	('Ungarn', 'Hungary'),
	('Türkei', 'Turkey'),
	('Tschechien', 'Czech Republic'),
	('Slowakei', 'Slovakia'),
	('Rumänien', 'Romania'),
	('Brasilien', 'Brazil'),
	('Israel', 'Israel'),
	('Russland', 'Russai'),
	('Tschad', 'Tchad'),
	('Ghana', 'Ghana'),
	('Estland', 'Estonia'),
	('Australien', 'Australia'),
	('Bulgarien', 'Bulgaria'),
	('Slowenien', 'Slovenia'),
	('Ukraine', 'Ukraine'),
	('Argentinien', 'Argentinia'),
	('Malta', 'Malta'),
	('Frankreich', 'France'),
	('Singapur', 'Singapore'),
	('China', 'China'),
	('Litauen', 'Litauania'),
	('Taiwan', 'Taiwan'),
	('Zypern', 'Cyprus'),
	('Aserbaidschan', 'Azerbaidjan'),
	('Kroatien', 'Croatia'),
	('Lettland', 'Latvia'),
	('Afghanistan', 'Afghanistan'),
	('Åland', 'Åland Islands'),
	('Albanien', 'Albania'),
	('Algerien', 'Algeria'),
	('Amerikanisch-Samoa', 'American Samoa'),
	('Andorra', 'Andorra'),
	('Angola', 'Angola'),
	('Anguilla', 'Anguilla'),
	('Antarktika', 'Antarctica'),
	('Antigua und Barbuda', 'Antigua And Barbuda'),
	('Armenien', 'Armenia'),
	('Aruba', 'Aruba'),
	('Bahamas', 'Bahamas'),
	('Bahrain', 'Bahrain'),
	('Bangladesch', 'Bangladesh'),
	('Barbados', 'Barbados'),
	('Weißrussland', 'Belarus'),
	('Belize', 'Belize'),
	('Benin', 'Benin'),
	('Bermuda', 'Bermuda'),
	('Bhutan', 'Bhutan'),
	('Bolivien', 'Bolivia (plurinational State Of)'),
	('Bonaire, Sint Eustatius und Saba', 'Bonaire, Sint Eustatius And Saba'),
	('Bosnien und Herzegowina', 'Bosnia And Herzegovina'),
	('Botswana', 'Botswana'),
	('Bouvetinsel', 'Bouvet Island'),
	('Britisches Territorium im Indischen Ozean', 'British Indian Ocean Territory'),
	('Kleinere Inselbesitzungen der Vereinigten Staaten', 'United States Minor Outlying Islands'),
	('Britische Jungferninseln', 'Virgin Islands (british)'),
	('Amerikanische Jungferninseln', 'Virgin Islands (u.s.)'),
	('Brunei', 'Brunei Darussalam'),
	('Burkina Faso', 'Burkina Faso'),
	('Burundi', 'Burundi'),
	('Kambodscha', 'Cambodia'),
	('Kamerun', 'Cameroon'),
	('Kap Verde', 'Cabo Verde'),
	('Kaimaninseln', 'Cayman Islands'),
	('Zentralafrikanische Republik', 'Central African Republic'),
	('Chile', 'Chile'),
	('Weihnachtsinsel', 'Christmas Island'),
	('Kokosinseln', 'Cocos (keeling) Islands'),
	('Kolumbien', 'Colombia'),
	('Union der Komoren', 'Comoros'),
	('Kongo', 'Congo'),
	('Kongo (Dem. Rep.)', 'Congo (democratic Republic Of The)'),
	('Cookinseln', 'Cook Islands'),
	('Costa Rica', 'Costa Rica'),
	('Kuba', 'Cuba'),
	('Curaçao', 'CuraÇao'),
	('Dschibuti', 'Djibouti'),
	('Dominica', 'Dominica'),
	('Dominikanische Republik', 'Dominican Republic'),
	('Ecuador', 'Ecuador'),
	('Ägypten', 'Egypt'),
	('El Salvador', 'El Salvador'),
	('Äquatorial-Guinea', 'Equatorial Guinea'),
	('Eritrea', 'Eritrea'),
	('Äthiopien', 'Ethiopia'),
	('Falklandinseln', 'Falkland Islands (malvinas)'),
	('Färöer-Inseln', 'Faroe Islands'),
	('Fidschi', 'Fiji'),
	('Französisch Guyana', 'French Guiana'),
	('Französisch-Polynesien', 'French Polynesia'),
	('Französische Süd- und Antarktisgebiete', 'French Southern Territories'),
	('Gabun', 'Gabon'),
	('Gambia', 'Gambia'),
	('Georgien', 'Georgia'),
	('Gibraltar', 'Gibraltar'),
	('Grönland', 'Greenland'),
	('Grenada', 'Grenada'),
	('Guadeloupe', 'Guadeloupe'),
	('Guam', 'Guam'),
	('Guatemala', 'Guatemala'),
	('Guernsey', 'Guernsey'),
	('Guinea', 'Guinea'),
	('Guinea-Bissau', 'Guinea-bissau'),
	('Guyana', 'Guyana'),
	('Haiti', 'Haiti'),
	('Heard und die McDonaldinseln', 'Heard Island And Mcdonald Islands'),
	('Heiliger Stuhl', 'Holy See'),
	('Honduras', 'Honduras'),
	('Hong Kong', 'Hong Kong'),
	('Indien', 'India'),
	('Indonesien', 'Indonesia'),
	('Elfenbeinküste', 'CÔte D\'ivoire'),
	('Iran', 'Iran (islamic Republic Of)'),
	('Irak', 'Iraq'),
	('Insel Man', 'Isle Of Man'),
	('Jamaika', 'Jamaica'),
	('Jersey', 'Jersey'),
	('Jordanien', 'Jordan'),
	('Kasachstan', 'Kazakhstan'),
	('Kenia', 'Kenya'),
	('Kiribati', 'Kiribati'),
	('Kuwait', 'Kuwait'),
	('Kirgisistan', 'Kyrgyzstan'),
	('Laos', 'Lao People\'s Democratic Republic'),
	('Libanon', 'Lebanon'),
	('Lesotho', 'Lesotho'),
	('Liberia', 'Liberia'),
	('Libyen', 'Libya'),
	('Macao', 'Macao'),
	('Mazedonien', 'Macedonia (the Former Yugoslav Republic Of)'),
	('Madagaskar', 'Madagascar'),
	('Malawi', 'Malawi'),
	('Malaysia', 'Malaysia'),
	('Malediven', 'Maldives'),
	('Mali', 'Mali'),
	('Marshallinseln', 'Marshall Islands'),
	('Martinique', 'Martinique'),
	('Mauretanien', 'Mauritania'),
	('Mauritius', 'Mauritius'),
	('Mayotte', 'Mayotte'),
	('Mexiko', 'Mexico'),
	('Mikronesien', 'Micronesia (federated States Of)'),
	('Moldawie', 'Moldova (republic Of)'),
	('Monaco', 'Monaco'),
	('Mongolei', 'Mongolia'),
	('Montenegro', 'Montenegro'),
	('Montserrat', 'Montserrat'),
	('Marokko', 'Morocco'),
	('Mosambik', 'Mozambique'),
	('Myanmar', 'Myanmar'),
	('Nauru', 'Nauru'),
	('Népal', 'Nepal'),
	('Neukaledonien', 'New Caledonia'),
	('Neuseeland', 'New Zealand'),
	('Nicaragua', 'Nicaragua'),
	('Niger', 'Niger'),
	('Nigeria', 'Nigeria'),
	('Niue', 'Niue'),
	('Norfolkinsel', 'Norfolk Island'),
	('Nordkorea', 'Korea (democratic People\'s Republic Of)'),
	('Nördliche Marianen', 'Northern Mariana Islands'),
	('Oman', 'Oman'),
	('Pakistan', 'Pakistan'),
	('Palau', 'Palau'),
	('Palästina', 'Palestine, State Of'),
	('Panama', 'Panama'),
	('Papua-Neuguinea', 'Papua New Guinea'),
	('Paraguay', 'Paraguay'),
	('Peru', 'Peru'),
	('Philippinen', 'Philippines'),
	('Pitcairn', 'Pitcairn'),
	('Puerto Rico', 'Puerto Rico'),
	('Katar', 'Qatar'),
	('Republic of Kosovo', 'Republic Of Kosovo'),
	('Réunion', 'RÉunion'),
	('Ruanda', 'Rwanda'),
	('Saint-Barthélemy', 'Saint BarthÉlemy'),
	('Sankt Helena', 'Saint Helena, Ascension And Tristan Da Cunha'),
	('St. Kitts und Nevis', 'Saint Kitts And Nevis'),
	('Saint Lucia', 'Saint Lucia'),
	('Saint Martin', 'Saint Martin (french Part)'),
	('Saint-Pierre und Miquelon', 'Saint Pierre And Miquelon'),
	('Saint Vincent und die Grenadinen', 'Saint Vincent And The Grenadines'),
	('Samoa', 'Samoa'),
	('San Marino', 'San Marino'),
	('São Tomé und Príncipe', 'Sao Tome And Principe'),
	('Saudi-Arabien', 'Saudi Arabia'),
	('Senegal', 'Senegal'),
	('Serbien', 'Serbia'),
	('Seychellen', 'Seychelles'),
	('Sierra Leone', 'Sierra Leone'),
	('Sint Maarten (niederl. Teil)', 'Sint Maarten (dutch Part)'),
	('Salomonen', 'Solomon Islands'),
	('Somalia', 'Somalia'),
	('Republik Südafrika', 'South Africa'),
	('Südgeorgien und die Südlichen Sandwichinseln', 'South Georgia And The South Sandwich Islands'),
	('Südkorea', 'Korea (republic Of)'),
	('Südsudan', 'South Sudan'),
	('Sri Lanka', 'Sri Lanka'),
	('Sudan', 'Sudan'),
	('Suriname', 'Suriname'),
	('Svalbard und Jan Mayen', 'Svalbard And Jan Mayen'),
	('Swasiland', 'Swaziland'),
	('Syrien', 'Syrian Arab Republic'),
	('Tadschikistan', 'Tajikistan'),
	('Tansania', 'Tanzania, United Republic Of'),
	('Thailand', 'Thailand'),
	('Timor-Leste', 'Timor-leste'),
	('Togo', 'Togo'),
	('Tokelau', 'Tokelau'),
	('Tonga', 'Tonga'),
	('Trinidad und Tobago', 'Trinidad And Tobago'),
	('Tunesien', 'Tunisia'),
	('Turkmenistan', 'Turkmenistan'),
	('Turks- und Caicosinseln', 'Turks And Caicos Islands'),
	('Tuvalu', 'Tuvalu'),
	('Uganda', 'Uganda'),
	('Uruguay', 'Uruguay'),
	('Usbekistan', 'Uzbekistan'),
	('Vanuatu', 'Vanuatu'),
	('Venezuela', 'Venezuela (bolivarian Republic Of)'),
	('Vietnam', 'Viet Nam'),
	('Wallis und Futuna', 'Wallis And Futuna'),
	('Westsahara', 'Western Sahara'),
	('Jemen', 'Yemen'),
	('Sambia', 'Zambia'),
	('Simbabwe', 'Zimbabwe');
